[package]
name = "dimple_data"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
anyhow = "1.0"
rusqlite = "0.36"
serde = { version = "1.0", features = ["derive"] }
serde_rusqlite = "0.39"
uuid = { version = "1.17", features = ["v7"] }
serde_json = "1.0"
rusqlite_migration = "2.2"
rust-s3 = { version = "0.33.0", features = ["sync-native-tls"], default-features = false }
base64 = "0.22.1"
age = "0.11.1"

[dev-dependencies]
env_logger = "0.11"
