[package]
name = "dimple_data"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { version = "0.4.27" }
env_logger = { version = "0.11.8" }
anyhow = "1.0.98"
rusqlite = { version = "0.36.0" }
serde = { version = "1.0.219", features = ["derive"] }
serde_rusqlite = "0.39.1"
uuid = { version = "1.17.0", features = ["v7"] }
serde_json = "1.0.140"
